CREATE TABLE [dbo].[User]
(
  [UserID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
  [FirstName] VARCHAR(50) NOT NULL,
  [LastName] VARCHAR(120) NOT NULL,
  [IDNumber] CHAR(13) UNIQUE NOT NULL,
  [GenderID] INT NOT NULL,
  [ContactID] INT NOT NULL,
  [UserRoleID] INT NOT NULL,
  [IsUserActive] BIT NOT NULL DEFAULT 1
)
GO

ALTER TABLE [dbo].[User]
ADD CONSTRAINT FK_UserRole FOREIGN KEY([UserRoleID]) REFERENCES [dbo].[UserRole]
GO

ALTER TABLE [dbo].[User]
ADD CONSTRAINT FK_UserRole FOREIGN KEY([GenderID]) REFERENCES [dbo].[Gender]
GO

ALTER TABLE [dbo].[User]
ADD CONSTRAINT FK_UserRole FOREIGN KEY([ContactID]) REFERENCES [dbo].[Contact]
GO


