# .github/workflows/sql-workflow.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/sql-action@v2.2.1
      with:        
        server-name: bursarysystem.database.windows.net 
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: 'BursaryDB/BursaryDB.sqlproj'
        action: 'publish'
